export const DATA_URUNLER = [
  {
    dovizCinsi:"TL",id: 1,
    ad: 'KABİN SÜSPANSİYONU 2/1',
    miktar: 1,
    birim: 'ADET',
    grup:'Kabin Karkası',
    urunSatirlar: [
      { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 140,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      {
        dovizCinsi:"TL",id: 3,
        ad: 'M10*20 C.S.P.R',
        miktar: 6,
        birim: 'TAKIM',
        birimFiyat: 3.23,
      },
      {
        dovizCinsi:"TL",id: 4,
        ad: 'M8*20 C.S.P.R',
        miktar: 40,
        birim: 'TAKIM',
        birimFiyat: 1.87,
      },
      {
        dovizCinsi:"TL",id: 5,
        ad: 'FREN BLOĞU ',
        miktar: 1,
        birim: 'ADET',
        birimFiyat: 3915,
      },
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 2, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 7,
        ad: 'KABİN PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 257.5,
      },
      { dovizCinsi:"TL",id: 8, ad: 'YAĞDANLIK	 ', miktar: 2, birim: 'ADET', birimFiyat: 40 },
      { dovizCinsi:"TL",id: 9, ad: 'RADANSA	 ', miktar: 4, birim: 'ADET', birimFiyat: 30 },
    ],
  },
  {
    dovizCinsi:"TL",id: 2,
    ad: 'KABİN SÜSPANSİYONU 1/1',
    miktar: 1,
    birim: 'ADET',
    grup:'Kabin Karkası',
    urunSatirlar: [
      { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 90,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      {
        dovizCinsi:"TL",id: 3,
        ad: 'M10*20 C.S.P.R',
        miktar: 6,
        birim: 'TAKIM',
        birimFiyat: 3.23,
      },

      {
        dovizCinsi:"TL",id: 5,
        ad: 'FREN BLOĞU ',
        miktar: 1,
        birim: 'ADET',
        birimFiyat: 3915,
      },
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 2, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 7,
        ad: 'KABİN PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 257.5,
      },
      { dovizCinsi:"TL",id: 8, ad: 'YAĞDANLIK	 ', miktar: 2, birim: 'ADET', birimFiyat: 40 },
      { dovizCinsi:"TL",id: 9, ad: 'RADANSA	 ', miktar: 4, birim: 'ADET', birimFiyat: 30 },
    ],
  },
  {
    dovizCinsi:"TL",id: 3,
    ad: 'AĞIRLIK SÜSPANSİYONU 1/1 TEK SIRA',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
      { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 40,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 7,
        ad: 'AĞIRLIK PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 286.25,
      },
    ],
  },
  {
    dovizCinsi:"TL",id: 4,
    ad: 'AĞIRLIK SÜSPANSİYONU 1/1 ÇİFT SIRA',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
      { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 70,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 10,
        ad: 'AĞIRLIK PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 286.25,
      },
    ],
  },
  {
    dovizCinsi:"TL",id: 5,
    ad: 'AĞIRLIK SÜSPANSİYONU 1/1 TEK SIRA DUBLEX',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
      { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 40,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1.5, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 10,
        ad: 'AĞIRLIK PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 286.25,
      },
    ],
  },
  {
    dovizCinsi:"TL",id: 6,
    ad: 'AĞIRLIK SÜSPANSİYONU 1/1 ÇİFT SIRA DUBLEX',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
        { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 40,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 2, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 10,
        ad: 'AĞIRLIK PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 286.25,
      },
    ],
  },
  {
    dovizCinsi:"TL",id: 7,
    ad: 'AĞIRLIK SÜSPANSİYONU 2/1 TEK SIRA',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
        { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
        {
          dovizCinsi:"TL",id: 2,
          ad: 'M12*30 C.S.P.R ',
          miktar: 60,
          birim: 'TAKIM',
          birimFiyat: 5.17,
        },
        {
            dovizCinsi:"TL",id: 4,
            ad: 'M8*20 C.S.P.R',
            miktar: 16,
            birim: 'TAKIM',
            birimFiyat: 1.87,
          },
        { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1, birim: 'KG', birimFiyat: 2.5 },
        {
          dovizCinsi:"TL",id: 10,
          ad: 'AĞIRLIK PATEN BLOĞU ',
          miktar: 4,
          birim: 'ADET',
          birimFiyat: 286.25,
        },
    ],
  },
  {
    dovizCinsi:"TL",id: 8,
    ad: 'AĞIRLIK SÜSPANSİYONU 2/1 ÇİFT SIRA',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
        { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
        {
          dovizCinsi:"TL",id: 2,
          ad: 'M12*30 C.S.P.R ',
          miktar: 80,
          birim: 'TAKIM',
          birimFiyat: 5.17,
        },
        {
            dovizCinsi:"TL",id: 4,
            ad: 'M8*20 C.S.P.R',
            miktar: 16,
            birim: 'TAKIM',
            birimFiyat: 1.87,
          },
        { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1, birim: 'KG', birimFiyat: 2.5 },
        {
          dovizCinsi:"TL",id: 10,
          ad: 'AĞIRLIK PATEN BLOĞU ',
          miktar: 4,
          birim: 'ADET',
          birimFiyat: 286.25,
        },
    ],
  },
  {
    dovizCinsi:"TL",id: 9,
    ad: 'AĞIRLIK SÜSPANSİYONU 2/1 TEK SIRA DUBLEX',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
        { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
        {
          dovizCinsi:"TL",id: 2,
          ad: 'M12*30 C.S.P.R ',
          miktar: 60,
          birim: 'TAKIM',
          birimFiyat: 5.17,
        },
        {
            dovizCinsi:"TL",id: 4,
            ad: 'M8*20 C.S.P.R',
            miktar: 16,
            birim: 'TAKIM',
            birimFiyat: 1.87,
          },
        { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1.5, birim: 'KG', birimFiyat: 2.5 },
        {
          dovizCinsi:"TL",id: 10,
          ad: 'AĞIRLIK PATEN BLOĞU ',
          miktar: 4,
          birim: 'ADET',
          birimFiyat: 286.25,
        },
    ],
  },
  {
    dovizCinsi:"TL",id: 10,
    ad: 'AĞIRLIK SÜSPANSİYONU 2/1 ÇİFT SIRA DUBLEX',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
        { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
        {
          dovizCinsi:"TL",id: 2,
          ad: 'M12*30 C.S.P.R ',
          miktar: 80,
          birim: 'TAKIM',
          birimFiyat: 5.17,
        },
        {
            dovizCinsi:"TL",id: 4,
            ad: 'M8*20 C.S.P.R',
            miktar: 16,
            birim: 'TAKIM',
            birimFiyat: 1.87,
          },
        { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 2, birim: 'KG', birimFiyat: 2.5 },
        {
          dovizCinsi:"TL",id: 10,
          ad: 'AĞIRLIK PATEN BLOĞU ',
          miktar: 4,
          birim: 'ADET',
          birimFiyat: 286.25,
        },
    ],
  },
];




export const URUNLER=[
    {
      dovizCinsi:"TL",id: 10,
      ad:"320 KG ESB KABİN",
      urunGrubu: 'kabin',
      miktar: 1,
      birim: 'ADET',
      urunBilesenler:[
        { id: 1, ad: 'SAC', miktar: 237.5, birim: 'KG', birimFiyat: 28,dovizCinsi:"TL", },
        { id: 2, ad: 'Boya', miktar: 237.5, birim: 'KG', birimFiyat: 28,dovizCinsi:"TL", },
        { id: 3, ad: '4lü led aydınlatma', miktar: 1, birim: 'takım', birimFiyat: 40,dovizCinsi:"USD", },
        { id: 4, ad: 'fan + muhafaza', miktar: 1, birim: 'takım', birimFiyat: 330.68,dovizCinsi:"TL", },
        { id: 5, ad: 'acil aydınlatma', miktar: 4, birim: 'adet', birimFiyat: 60,dovizCinsi:"TL", },
        { id: 6, ad: 'ayna', miktar: 2., birim: 'M^2', birimFiyat: 600,dovizCinsi:"TL", },
        { id: 7, ad: 'korkuluk', miktar:36.06, birim: 'KG', birimFiyat: 30,dovizCinsi:"TL", },
        { id: 8, ad: 'tutamak', miktar: 1.9, birim: 'M', birimFiyat: 5.30,dovizCinsi:"USD", },
        { id: 9, ad: 'etek sacı', miktar: 1, birim: 'adet', birimFiyat: 300,dovizCinsi:"TL", },
        { id: 10, ad: 'alüminyum ön eşik', miktar: 0.62, birim: 'KG', birimFiyat: 133,dovizCinsi:"TL", },
        { id: 11, ad: 'tavan menteşe+kilit', miktar: 2, birim: 'takım', birimFiyat: 250,dovizCinsi:"TL", },
        { id: 12, ad: 'pvc kaplama', miktar:1, birim: 'KG', birimFiyat: 0,dovizCinsi:"TL", },
        { id: 13, ad: 'taban suntası 18 mm', miktar: 0.62, birim: 'KG', birimFiyat: 750,dovizCinsi:"TL", },
        { id: 14, ad: 'muhtelif gider', miktar: 0.62, birim: 'KG', birimFiyat: 133,dovizCinsi:"TL", },
      ]
    }
]
