export const DATA_URUNLER = [
  {
    dovizCinsi:"TL",id: 1,
    ad: 'KABİN SÜSPANSİYONU 2/1',
    miktar: 1,
    birim: 'ADET',
    grup:'Kabin Karkası',
    urunSatirlar: [
      { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 140,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      {
        dovizCinsi:"TL",id: 3,
        ad: 'M10*20 C.S.P.R',
        miktar: 6,
        birim: 'TAKIM',
        birimFiyat: 3.23,
      },
      {
        dovizCinsi:"TL",id: 4,
        ad: 'M8*20 C.S.P.R',
        miktar: 40,
        birim: 'TAKIM',
        birimFiyat: 1.87,
      },
      {
        dovizCinsi:"TL",id: 5,
        ad: 'FREN BLOĞU ',
        miktar: 1,
        birim: 'ADET',
        birimFiyat: 3915,
      },
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 2, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 7,
        ad: 'KABİN PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 257.5,
      },
      { dovizCinsi:"TL",id: 8, ad: 'YAĞDANLIK	 ', miktar: 2, birim: 'ADET', birimFiyat: 40 },
      { dovizCinsi:"TL",id: 9, ad: 'RADANSA	 ', miktar: 4, birim: 'ADET', birimFiyat: 30 },
    ],
  },
  {
    dovizCinsi:"TL",id: 2,
    ad: 'KABİN SÜSPANSİYONU 1/1',
    miktar: 1,
    birim: 'ADET',
    grup:'Kabin Karkası',
    urunSatirlar: [
      { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 90,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      {
        dovizCinsi:"TL",id: 3,
        ad: 'M10*20 C.S.P.R',
        miktar: 6,
        birim: 'TAKIM',
        birimFiyat: 3.23,
      },

      {
        dovizCinsi:"TL",id: 5,
        ad: 'FREN BLOĞU ',
        miktar: 1,
        birim: 'ADET',
        birimFiyat: 3915,
      },
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 2, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 7,
        ad: 'KABİN PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 257.5,
      },
      { dovizCinsi:"TL",id: 8, ad: 'YAĞDANLIK	 ', miktar: 2, birim: 'ADET', birimFiyat: 40 },
      { dovizCinsi:"TL",id: 9, ad: 'RADANSA	 ', miktar: 4, birim: 'ADET', birimFiyat: 30 },
    ],
  },
  {
    dovizCinsi:"TL",id: 3,
    ad: 'AĞIRLIK SÜSPANSİYONU 1/1 TEK SIRA',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
      { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 40,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 7,
        ad: 'AĞIRLIK PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 286.25,
      },
    ],
  },
  {
    dovizCinsi:"TL",id: 4,
    ad: 'AĞIRLIK SÜSPANSİYONU 1/1 ÇİFT SIRA',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
      { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 70,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 10,
        ad: 'AĞIRLIK PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 286.25,
      },
    ],
  },
  {
    dovizCinsi:"TL",id: 5,
    ad: 'AĞIRLIK SÜSPANSİYONU 1/1 TEK SIRA DUBLEX',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
      { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 40,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1.5, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 10,
        ad: 'AĞIRLIK PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 286.25,
      },
    ],
  },
  {
    dovizCinsi:"TL",id: 6,
    ad: 'AĞIRLIK SÜSPANSİYONU 1/1 ÇİFT SIRA DUBLEX',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
        { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
      {
        dovizCinsi:"TL",id: 2,
        ad: 'M12*30 C.S.P.R ',
        miktar: 40,
        birim: 'TAKIM',
        birimFiyat: 5.17,
      },
      
      { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 2, birim: 'KG', birimFiyat: 2.5 },
      {
        dovizCinsi:"TL",id: 10,
        ad: 'AĞIRLIK PATEN BLOĞU ',
        miktar: 4,
        birim: 'ADET',
        birimFiyat: 286.25,
      },
    ],
  },
  {
    dovizCinsi:"TL",id: 7,
    ad: 'AĞIRLIK SÜSPANSİYONU 2/1 TEK SIRA',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
        { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
        {
          dovizCinsi:"TL",id: 2,
          ad: 'M12*30 C.S.P.R ',
          miktar: 60,
          birim: 'TAKIM',
          birimFiyat: 5.17,
        },
        {
            dovizCinsi:"TL",id: 4,
            ad: 'M8*20 C.S.P.R',
            miktar: 16,
            birim: 'TAKIM',
            birimFiyat: 1.87,
          },
        { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1, birim: 'KG', birimFiyat: 2.5 },
        {
          dovizCinsi:"TL",id: 10,
          ad: 'AĞIRLIK PATEN BLOĞU ',
          miktar: 4,
          birim: 'ADET',
          birimFiyat: 286.25,
        },
    ],
  },
  {
    dovizCinsi:"TL",id: 8,
    ad: 'AĞIRLIK SÜSPANSİYONU 2/1 ÇİFT SIRA',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
        { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
        {
          dovizCinsi:"TL",id: 2,
          ad: 'M12*30 C.S.P.R ',
          miktar: 80,
          birim: 'TAKIM',
          birimFiyat: 5.17,
        },
        {
            dovizCinsi:"TL",id: 4,
            ad: 'M8*20 C.S.P.R',
            miktar: 16,
            birim: 'TAKIM',
            birimFiyat: 1.87,
          },
        { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1, birim: 'KG', birimFiyat: 2.5 },
        {
          dovizCinsi:"TL",id: 10,
          ad: 'AĞIRLIK PATEN BLOĞU ',
          miktar: 4,
          birim: 'ADET',
          birimFiyat: 286.25,
        },
    ],
  },
  {
    dovizCinsi:"TL",id: 9,
    ad: 'AĞIRLIK SÜSPANSİYONU 2/1 TEK SIRA DUBLEX',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
        { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
        {
          dovizCinsi:"TL",id: 2,
          ad: 'M12*30 C.S.P.R ',
          miktar: 60,
          birim: 'TAKIM',
          birimFiyat: 5.17,
        },
        {
            dovizCinsi:"TL",id: 4,
            ad: 'M8*20 C.S.P.R',
            miktar: 16,
            birim: 'TAKIM',
            birimFiyat: 1.87,
          },
        { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 1.5, birim: 'KG', birimFiyat: 2.5 },
        {
          dovizCinsi:"TL",id: 10,
          ad: 'AĞIRLIK PATEN BLOĞU ',
          miktar: 4,
          birim: 'ADET',
          birimFiyat: 286.25,
        },
    ],
  },
  {
    dovizCinsi:"TL",id: 10,
    ad: 'AĞIRLIK SÜSPANSİYONU 2/1 ÇİFT SIRA DUBLEX',
    miktar: 1,
    birim: 'ADET',
    grup:'Ağırlık Karkası',
    urunSatirlar: [
        { dovizCinsi:"TL",id: 1, ad: 'SAC', miktar: 1, birim: 'KG', birimFiyat: 28 },
        {
          dovizCinsi:"TL",id: 2,
          ad: 'M12*30 C.S.P.R ',
          miktar: 80,
          birim: 'TAKIM',
          birimFiyat: 5.17,
        },
        {
            dovizCinsi:"TL",id: 4,
            ad: 'M8*20 C.S.P.R',
            miktar: 16,
            birim: 'TAKIM',
            birimFiyat: 1.87,
          },
        { dovizCinsi:"EURO",id: 6, ad: 'BOYA ', miktar: 2, birim: 'KG', birimFiyat: 2.5 },
        {
          dovizCinsi:"TL",id: 10,
          ad: 'AĞIRLIK PATEN BLOĞU ',
          miktar: 4,
          birim: 'ADET',
          birimFiyat: 286.25,
        },
    ],
  },
];




export const URUNLER=[
    {
      id: 1,
      ad:"320 KG ESB KABİN",
      urunGrubu: 'kabin',
      miktar: 1,
      birim: 'ADET',
      dovizCinsi:"TL",
      urunBilesenler:[
        { id: 1, ad: 'SAC', miktar: 237.5, birim: 'KG', birimFiyat: 28,dovizCinsi:"TL", },
        { id: 2, ad: 'Boya', miktar:38, birim: 'M^2', birimFiyat: 2.5,dovizCinsi:"EURO", },
        { id: 3, ad: '4lü led aydınlatma', miktar: 1, birim: 'takım', birimFiyat: 40,dovizCinsi:"USD", },
        { id: 4, ad: 'fan + muhafaza', miktar: 1, birim: 'takım', birimFiyat: 330.68,dovizCinsi:"TL", },
        { id: 5, ad: 'acil aydınlatma', miktar: 4, birim: 'adet', birimFiyat: 60,dovizCinsi:"TL", },
        { id: 6, ad: 'ayna', miktar: 2, birim: 'M^2', birimFiyat: 600,dovizCinsi:"TL", },
        { id: 7, ad: 'korkuluk', miktar:36.06, birim: 'KG', birimFiyat: 30,dovizCinsi:"TL", },
        { id: 8, ad: 'tutamak', miktar: 1.9, birim: 'M', birimFiyat: 5.30,dovizCinsi:"USD", },
        { id: 9, ad: 'etek sacı', miktar: 1, birim: 'adet', birimFiyat: 300,dovizCinsi:"TL", },
        { id: 10, ad: 'alüminyum ön eşik', miktar: 0.62, birim: 'KG', birimFiyat: 133,dovizCinsi:"TL", },
        { id: 11, ad: 'tavan menteşe+kilit', miktar: 2, birim: 'takım', birimFiyat: 250,dovizCinsi:"TL", },
        { id: 12, ad: 'pvc kaplama', miktar:1, birim: 'KG', birimFiyat: 0,dovizCinsi:"TL", },
        { id: 13, ad: 'taban suntası 18 mm', miktar: 1, birim: 'KG', birimFiyat: 730,dovizCinsi:"TL", },
        { id: 14, ad: 'muhtelif gider', miktar: 1, birim: 'takım', birimFiyat: 2000,dovizCinsi:"TL", },
        { id: 23, ad: 'TUTAMAK BAĞLAMA APARATI VE TAPASI', miktar: 1, birim: 'ADET', birimFiyat: 50 ,dovizCinsi:"USD",},
        { id: 24, ad: 'M8*30 C.S.P.R',miktar: 36,birim: 'adet',birimFiyat: 3.5,dovizCinsi:"TL",},
        { id: 25, ad: 'M6*30 C.S.P.R',miktar: 24,birim: 'adet',birimFiyat: 3,dovizCinsi:"TL",},
        { id: 26, ad: '25*25*1.5 MM PROFİL(KORKULUK İÇİN)',miktar: 5.8, birim: 'M',  birimFiyat: 34.31,dovizCinsi:"TL",},
      ]
    },

    {
      id: 2,
      ad:"Kabin Süspansiyonu 2/1",
      urunGrubu: 'kabin',
      miktar: 1,
      birim: 'ADET',
      dovizCinsi:"TL",
      urunBilesenler: [
        { id: 1, ad: 'SAC', miktar: 392.72, birim: 'KG', birimFiyat: 28 ,dovizCinsi:"TL",},
        { id: 16,ad: 'M12*30 C.S.P.R ',  miktar: 140,  birim: 'TAKIM',  birimFiyat: 5.17,dovizCinsi:"TL",},
        { id: 17,ad: 'M10*20 C.S.P.R',  miktar: 6,  birim: 'TAKIM',  birimFiyat: 3.23,dovizCinsi:"TL",},
        { id: 18,ad: 'M8*20 C.S.P.R',  miktar: 40,  birim: 'TAKIM',  birimFiyat: 1.87,dovizCinsi:"TL",},
        { id: 19,ad: 'FREN BLOĞU ',  miktar: 1,  birim: 'ADET',  birimFiyat: 3915,dovizCinsi:"TL",},
        { id: 2, ad: 'BOYA ', miktar: 2, birim: 'KG', birimFiyat: 2.5 ,dovizCinsi:"EURO",},
        { id: 21, ad: 'KABİN PATEN BLOĞU ',  miktar: 4,  birim: 'ADET',  birimFiyat: 257.5,dovizCinsi:"TL",},
        { id: 22, ad: 'YAĞDANLIK	 ', miktar: 2, birim: 'ADET', birimFiyat: 40,dovizCinsi:"TL", },
        { id: 23, ad: 'RADANSA	 ', miktar: 4, birim: 'ADET', birimFiyat: 30 ,dovizCinsi:"TL",},
      ],
    },

    {
      id: 3,
      ad:"Mekanik Kabin Butonu",
      urunGrubu: 'Kabin Butonu',
      miktar: 1,
      birim: 'ADET',
      dovizCinsi:"TL",
      urunBilesenler:[
        { id: 1, ad: 'SAC', miktar:6.5, birim: 'KG', birimFiyat: 28,dovizCinsi:"TL", },
        { id: 27, ad: 'Boya',miktar:0.77,birim: 'M^2', birimFiyat: 3,dovizCinsi:"EURO", },
        { id: 28, ad: 'KAPAK SATİNE 1.5MM',miktar:5.75,birim: 'KG', birimFiyat: 2.85,dovizCinsi:"USD", },
        { id: 29, ad: 'BUTON KARTI KIRMIZI LED',miktar:7,birim: 'adet', birimFiyat:1.5,dovizCinsi:"USD", },
        { id: 30, ad: 'BUTON KASA(PLASTİK GRUP)',miktar:7,birim: 'TAKIM', birimFiyat:10,dovizCinsi:"TL", },
        { id: 31, ad: 'GDOT 6 GÖSTERGE',miktar:1,birim: 'adet', birimFiyat:83,dovizCinsi:"USD", },
        { id: 32, ad: 'CPC KARTI',miktar:1,birim: 'adet', birimFiyat:28,dovizCinsi:"USD", },
        { id: 33, ad: '0.22*4 SOKETLİ KABLO (1MT)',miktar:7,birim: 'M', birimFiyat:10,dovizCinsi:"TL", },
        { id: 34, ad: '0.22*4 SOKETLİ KABLO (1.6MT)',miktar:1.6,birim: 'M', birimFiyat:10,dovizCinsi:"TL", },
        { id: 35, ad: '(CBI2) 0.22*4 SOKETLİ KABLO (2MT)',miktar:2,birim: 'M', birimFiyat:10,dovizCinsi:"TL", },
        { id: 36, ad: 'İNTERCOM TAKIM',birim: 'TAKIM', miktar:1,birimFiyat:450,dovizCinsi:"TL", },
        { id: 37, ad: 'MUHTELİF GİDERLER',birim: 'TAKIM',miktar:1, birimFiyat:250,dovizCinsi:"TL", },
        { id: 38, ad: 'MENTŞE',miktar:2,birim: 'adet', birimFiyat:1.5,dovizCinsi:"USD", },
        { id: 39, ad: 'KİLİT SİSTEMİ',miktar:1,birim: 'adet', birimFiyat:100,dovizCinsi:"USD", },
      ]
    },
    {
      id: 4,
      ad:"Standart Kat Butonu",
      urunGrubu: 'Kat Butonu',
      miktar: 1,
      birim: 'ADET',
      dovizCinsi:"TL",
      urunBilesenler:[
        { id: 40, ad: 'YBCD3X GÖSTERGE',miktar:1,birim: 'adet', birimFiyat:15.82,dovizCinsi:"USD", },
        { id: 41, ad: 'BUTON KARTI KIRMIZI LED',miktar:1,birim: 'adet', birimFiyat:1.5,dovizCinsi:"USD", },
        { id: 42, ad: 'BUTON KASA(PLASTİK GRUP)',miktar:1,birim: 'adet', birimFiyat:10,dovizCinsi:"TL", },
        { id: 43, ad: 'BUTON KASASI SATİNE',miktar:0.55,birim: 'KG', birimFiyat:2.85,dovizCinsi:"USD", },
        { id: 44, ad: '0.22*4 SOKETLİ KABLO 10CM',miktar:0.1,birim: 'M', birimFiyat:10,dovizCinsi:"TL", },
        { id: 45, ad: 'BUTON MUHTELİF GİDERLER',miktar:1,birim: 'takım', birimFiyat:50,dovizCinsi:"TL", },
      ]
    },
    {
      id: 5,
      ad:"SIVA ÜSTÜ TEK DÜĞME GÖSTERGESİZ (SATİNE)",
      urunGrubu: 'Kat Butonu',
      miktar: 1,
      birim: 'ADET',
      dovizCinsi:"TL",
      urunBilesenler:[
        { id: 41, ad: 'BUTON KARTI KIRMIZI LED',miktar:1,birim: 'adet', birimFiyat:1.5,dovizCinsi:"USD", },
        { id: 42, ad: 'BUTON KASA(PLASTİK GRUP)',miktar:1,birim: 'adet', birimFiyat:10,dovizCinsi:"TL", },
        { id: 43, ad: 'BUTON KASASI SATİNE',miktar:0.55,birim: 'KG', birimFiyat:2.85,dovizCinsi:"USD", },
        { id: 44, ad: '0.22*4 SOKETLİ KABLO 10CM',miktar:0.1,birim: 'M', birimFiyat:10,dovizCinsi:"TL", },
        { id: 45, ad: 'BUTON MUHTELİF GİDERLER',miktar:1,birim: 'takım', birimFiyat:50,dovizCinsi:"TL", },
      ]
    },
    {
      id: 6,
      ad:"AĞIRLIK ARKADA DUVARDAN ŞASE",
      urunGrubu: 'suspansiyon',
      miktar: 1,
      birim: 'ADET',
      dovizCinsi:"TL",
      urunBilesenler:[
        { id: 46, ad: 'MAKİNE PLAKASI',miktar:15,birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
        { id: 48, ad: 'FİXPUNT 1',miktar:12,birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
        { id: 49, ad: 'FİXPUNT 2',miktar:12,birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
        { id: 50, ad: 'FİXPUNT 1 BAYRAK',miktar:4,birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
        { id: 51, ad: 'MP BAYRAK',birim: 'KG',miktar:9, birimFiyat:28,dovizCinsi:"TL", },
        { id: 52, ad: 'RP BAYRAK',birim: 'KG',miktar:2, birimFiyat:28,dovizCinsi:"TL", },
        { id: 53, ad: 'REGÜLATOR PLAKA',birim: 'KG', miktar:7,birimFiyat:28,dovizCinsi:"TL", },
        { id: 54, ad: '160 DUVAR KONSOL',birim: 'KG',miktar:20, birimFiyat:28,dovizCinsi:"TL", },
        { id: 55, ad: '160 NPU KONSOL',birim: 'KG',miktar:20, birimFiyat:28,dovizCinsi:"TL", },
        { id: 56, ad: '120 DUVAR KONS',birim: 'KG',miktar:16, birimFiyat:28,dovizCinsi:"TL", },
        { id: 57, ad: '120 NPU KONSOL',birim: 'KG',miktar:6, birimFiyat:28,dovizCinsi:"TL", },
        { id: 58, ad: '120 NPU',birim: 'KG',miktar:120, birimFiyat:28,dovizCinsi:"TL", },
        { id: 59, ad: 'M14*60 C.S.P.R',miktar:16,birim: 'adet', birimFiyat:24,dovizCinsi:"TL", },
        { id: 60, ad: 'M16*137 KLİPS DÜBEL',miktar:50,birim: 'adet', birimFiyat:43.53,dovizCinsi:"TL", },
      ]
    },
    {
      id: 7,
      ad:"AĞIRLIK ARKADA DUVARDAN ŞASE",
      urunGrubu: 'suspansiyon',
      miktar: 1,
      birim: 'ADET',
      dovizCinsi:"TL",
      urunBilesenler:[
        { id: 46, ad: 'MAKİNE PLAKASI',miktar:15,birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
        { id: 48, ad: 'FİXPUNT 1',miktar:12,birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
        { id: 49, ad: 'FİXPUNT 2',miktar:12,birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
        { id: 50, ad: 'FİXPUNT 1 BAYRAK',miktar:4,birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
        { id: 51, ad: 'MP BAYRAK',birim: 'KG',miktar:9, birimFiyat:28,dovizCinsi:"TL", },
        { id: 52, ad: 'RP BAYRAK',birim: 'KG',miktar:2, birimFiyat:28,dovizCinsi:"TL", },
        { id: 53, ad: 'REGÜLATOR PLAKA',birim: 'KG', miktar:7,birimFiyat:28,dovizCinsi:"TL", },
        { id: 54, ad: '160 DUVAR KONSOL',birim: 'KG',miktar:20, birimFiyat:28,dovizCinsi:"TL", },
        { id: 55, ad: '160 NPU KONSOL',birim: 'KG',miktar:20, birimFiyat:28,dovizCinsi:"TL", },
        { id: 56, ad: '120 DUVAR KONS',birim: 'KG',miktar:16, birimFiyat:28,dovizCinsi:"TL", },
        { id: 57, ad: '120 NPU KONSOL',birim: 'KG',miktar:6, birimFiyat:28,dovizCinsi:"TL", },
        { id: 58, ad: '120 NPU',birim: 'KG',miktar:60, birimFiyat:28,dovizCinsi:"TL", },
        { id: 61, ad: '140 NPU',birim: 'adet',miktar:70, birimFiyat:28,dovizCinsi:"TL", },
        { id: 59, ad: 'M14*60 C.S.P.R',miktar:16,birim: 'adet', birimFiyat:24,dovizCinsi:"TL", },
        { id: 60, ad: 'M16*137 KLİPS DÜBEL',miktar:50,birim: 'adet', birimFiyat:43.53,dovizCinsi:"TL", },
      ]
    },
]

export const DOVIZ=[
  {id:1,dovizCinsi:"TL",deger:1},
  {id:1,dovizCinsi:"USD",deger:33.25},
  {id:1,dovizCinsi:"EURO",deger:36.25},
]
export const STOKLAR=[
  { id: 1, ad: 'SAC', birim: 'KG', birimFiyat: 28,dovizCinsi:"TL", },
  { id: 2, ad: 'Boya',birim: 'M^2', birimFiyat: 2.5,dovizCinsi:"EURO", },
  { id: 3, ad: '4lü led aydınlatma', birim: 'takım', birimFiyat: 40,dovizCinsi:"USD", },
  { id: 4, ad: 'fan + muhafaza',  birim: 'takım', birimFiyat: 330.68,dovizCinsi:"TL", },
  { id: 5, ad: 'acil aydınlatma',  birim: 'adet', birimFiyat: 60,dovizCinsi:"TL", },
  { id: 6, ad: 'ayna', birim: 'M^2', birimFiyat: 600,dovizCinsi:"TL", },
  { id: 7, ad: 'korkuluk', birim: 'KG', birimFiyat: 30,dovizCinsi:"TL", },
  { id: 8, ad: 'tutamak', birim: 'M', birimFiyat: 5.30,dovizCinsi:"USD", },
  { id: 9, ad: 'etek sacı', birim: 'adet', birimFiyat: 300,dovizCinsi:"TL", },
  { id: 10, ad: 'alüminyum ön eşik',  birim: 'KG', birimFiyat: 133,dovizCinsi:"TL", },
  { id: 11, ad: 'tavan menteşe+kilit', birim: 'takım', birimFiyat: 250,dovizCinsi:"TL", },
  { id: 12, ad: 'pvc kaplama',  birim: 'KG', birimFiyat: 0,dovizCinsi:"TL", },
  { id: 13, ad: 'taban suntası 18 mm',  birim: 'KG', birimFiyat: 730,dovizCinsi:"TL", },
  { id: 14, ad: 'muhtelif gider',  birim: 'takım', birimFiyat: 2000,dovizCinsi:"TL", },
  { id: 15, ad: '6lı led aydınlatma', birim: 'takım', birimFiyat: 54,dovizCinsi:"USD", },
  { id: 16, ad: 'M12*30 C.S.P.R ', birim: 'TAKIM',  birimFiyat: 5.17,dovizCinsi:"TL",},
  { id: 17, ad: 'M10*20 C.S.P.R',   birim: 'TAKIM',  birimFiyat: 3.23,dovizCinsi:"TL",},
  { id: 18, ad: 'M8*20 C.S.P.R',   birim: 'TAKIM',  birimFiyat: 1.87,dovizCinsi:"TL",},
  { id: 19, ad: 'FREN BLOĞU',   birim: 'ADET',  birimFiyat: 3915,dovizCinsi:"TL",},
  { id: 20, ad: 'KABİN PATEN BLOĞU',    birim: 'ADET',  birimFiyat: 257.5,dovizCinsi:"TL",},
  { id: 21, ad: 'YAĞDANLIK',  birim: 'ADET', birimFiyat: 40,dovizCinsi:"TL", },
  { id: 22, ad: 'RADANSA',  birim: 'ADET', birimFiyat: 30 ,dovizCinsi:"TL",},
  { id: 23, ad: 'TUTAMAK BAĞLAMA APARATI VE TAPASI', birim: 'ADET', birimFiyat: 50 ,dovizCinsi:"USD",},
  { id: 24, ad: 'M8*30 C.S.P.R', birim: 'adet',birimFiyat: 3.5,dovizCinsi:"TL",},
  { id: 25, ad: 'M6*30 C.S.P.R', birim: 'adet',birimFiyat: 3,dovizCinsi:"TL",},
  { id: 26, ad: '25*25*1.5 MM PROFİL(KORKULUK İÇİN)', birim: 'M',  birimFiyat: 34.31,dovizCinsi:"TL",},
  { id: 27, ad: 'Boya',birim: 'M^2', birimFiyat: 3,dovizCinsi:"EURO", },
  { id: 28, ad: 'KAPAK SATİNE 1.5MM',birim: 'KG', birimFiyat: 2.85,dovizCinsi:"USD", },
  { id: 29, ad: 'BUTON KARTI KIRMIZI LED',birim: 'adet', birimFiyat:1.5,dovizCinsi:"USD", },
  { id: 30, ad: 'BUTON KASA(PLASTİK GRUP)',birim: 'TAKIM', birimFiyat:10,dovizCinsi:"TL", },
  { id: 31, ad: 'GDOT 6 GÖSTERGE',birim: 'adet', birimFiyat:83,dovizCinsi:"USD", },
  { id: 32, ad: 'CPC KARTI',birim: 'adet', birimFiyat:28,dovizCinsi:"USD", },
  { id: 33, ad: '0.22*4 SOKETLİ KABLO (1MT)',birim: 'M', birimFiyat:10,dovizCinsi:"TL", },
  { id: 34, ad: '0.22*4 SOKETLİ KABLO (1.6MT)',birim: 'M', birimFiyat:10,dovizCinsi:"TL", },
  { id: 35, ad: '(CBI2) 0.22*4 SOKETLİ KABLO (2MT)',birim: 'M', birimFiyat:10,dovizCinsi:"TL", },
  { id: 36, ad: 'İNTERCOM TAKIM',birim: 'TAKIM', birimFiyat:450,dovizCinsi:"TL", },
  { id: 37, ad: 'MUHTELİF GİDERLER',birim: 'TAKIM', birimFiyat:250,dovizCinsi:"TL", },
  { id: 38, ad: 'MENTŞE',birim: 'adet', birimFiyat:1.5,dovizCinsi:"USD", },
  { id: 39, ad: 'KİLİT SİSTEMİ',birim: 'adet', birimFiyat:100,dovizCinsi:"TL", },
  { id: 40, ad: 'YBCD3X GÖSTERGE',birim: 'adet', birimFiyat:15.82,dovizCinsi:"USD", },
  { id: 41, ad: 'BUTON KARTI KIRMIZI LED',birim: 'adet', birimFiyat:1.5,dovizCinsi:"USD", },
  { id: 42, ad: 'BUTON KASA(PLASTİK GRUP)',birim: 'adet', birimFiyat:10,dovizCinsi:"TL", },
  { id: 43, ad: 'BUTON KASASI SATİNE',birim: 'KG', birimFiyat:2.85,dovizCinsi:"USD", },
  { id: 44, ad: '0.22*4 SOKETLİ KABLO 10CM',birim: 'M', birimFiyat:10,dovizCinsi:"TL", },
  { id: 45, ad: 'BUTON MUHTELİF GİDERLER',birim: 'takım', birimFiyat:50,dovizCinsi:"TL", },
  { id: 46, ad: 'MAKİNE PLAKASI',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 47, ad: 'MAKİNE',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 48, ad: 'FİXPUNT 1',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 49, ad: 'FİXPUNT 2',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 50, ad: 'FİXPUNT 1 BAYRAK',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 51, ad: 'MP BAYRAK',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 52, ad: 'RP BAYRAK',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 53, ad: 'REGÜLATOR PLAKA',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 54, ad: '160 DUVAR KONSOL',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 55, ad: '160 NPU KONSOL',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 56, ad: '120 DUVAR KONS',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 57, ad: '120 NPU KONSOL',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 58, ad: '120 NPU',birim: 'KG', birimFiyat:28,dovizCinsi:"TL", },
  { id: 59, ad: 'M14*60 C.S.P.R',birim: 'adet', birimFiyat:24,dovizCinsi:"TL", },
  { id: 60, ad: 'M16*137 KLİPS DÜBEL',birim: 'adet', birimFiyat:43.53,dovizCinsi:"TL", },
  { id: 61, ad: '140 NPU',birim: 'adet', birimFiyat:28,dovizCinsi:"TL", },
]
export const KABIN_VARYANTLAR=[
  {id:1,urunId:1,urunGrubu:"Kabin",model:"ESB KABIN",kapasite:320},
]
export const SUSPANSIYON_VARYANTLAR=[
  {id:1,urunId:2,urunGrubu:"Süspansiyon",karkasTipi: 'Kabin Karkası',kapasite: "<1250",askiTipi: '2/1',karkasSekli:null,rayArasi: '3170',kosebent: 20,},
]
export const BUTON_VARYANTLAR=[
  {id:1,urunId:3,urunGrubu:"Buton",durakSayisi: 2,butonTipi:'Kabin Butonu',butonCesidi:'Mekanik'},
  {id:2,urunId:4,urunGrubu:"Buton",durakSayisi: null,butonTipi:'Kat Butonu',butonCesidi:'Standart'},
]
export const MAKINE_SASESI_VARYANTLAR=[
  {id:1,urunId:6,saseTipi:"Ağırlık Arkada Duvardan Şase",kapasite: 320,},
  {id:2,urunId:6,saseTipi:"Ağırlık Arkada Duvardan Şase",kapasite: 450,},
  {id:3,urunId:7,saseTipi:"Ağırlık Arkada Duvardan Şase",kapasite: 630,},
]




